name: resq_connect
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  
  geolocator: ^10.1.0
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  avatar_glow: ^2.0.2
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  http: ^1.1.2
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  dotted_border: ^2.0.0+3
  dio: ^5.3.3  
  flutter_polyline_points: ^2.0.0
  flutter_dotenv: ^5.1.0
  google_maps_flutter: ^2.2.2
  device_info:   
  permission_handler: ^11.0.0  
  image_picker: ^1.0.5
  multiple_images_picker: ^1.0.1
  http_parser: ^4.0.2
  geocoding: ^2.1.0
  flutter_screenutil: ^5.6.1
  lottie: ^3.1.2
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/resq_icon.png"
  min_sdk_android: 21 




flutter:

  
  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/dtypeImages/

 
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf 
  

